# Generated by Django 5.2.3 on 2026-07-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bella', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
