# Generated by Django 5.2.3 on 2026-08-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bella', '0007_order_delivered_at_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
