# Generated by Django 5.2.3 on 2026-08-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bella', '0008_order_delivery_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Black, Burgundy, Honey Blonde', max_length=50)),
                ('hex_code', models.CharField(help_text='Swatch colour, e.g. #1A1A1A', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='Bella.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
