# Generated by Django 5.2.3 on 2026-08-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bella', '0009_productcolour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colour_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colour_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
