# Generated by Django 5.2.3 on 2026-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bella', '0010_orderitem_colour_hex_orderitem_colour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_request',
            field=models.TextField(blank=True),
        ),
    ]
