# Generated by Django 5.2.3 on 2026-08-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bella', '0012_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master switch - turn off to stop all manager emails.'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='notify_contact_messages',
            field=models.BooleanField(default=True, help_text='Email me when someone submits the contact form.'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='notify_new_orders',
            field=models.BooleanField(default=True, help_text='Email me when a customer places a new order.'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='notify_new_reviews',
            field=models.BooleanField(default=True, help_text='Email me when a new product or store review is submitted for approval.'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'Match system')], default='light', help_text='Applied across the whole manager area, on every device you sign into.', max_length=10),
        ),
    ]
